### PR TITLE
Add gpseq-1.0

### LINKED ISSUE #245: Add gp-seq Documentation
"Gpseq is a GObject utility library providing parallel data processing."  
  
[Repo](https://gitlab.com/kosmospredanie/gpseq)
GitLab Pages hosted [Docs](https://kosmospredanie.gitlab.io/-/gpseq/-/jobs/246503199/artifacts/valadoc/gpseq-1.0/index.htm)
```vala
using Gpseq;

void main () {
	string[] array = {"dog", "cat", "pig", "boar", "bear"};
	Seq.of_array<string>(array)
		.parallel()
		.filter(g => g.length == 3)
		.map<string>(g => g.up())
		.foreach(g => print("%s\n", g))
		.wait(); // Gpseq.Future.wait() throws Error
}

// (possibly unordered) output:
// DOG
// CAT
// PIG
```

### PR DESCRIPTION
**Pull request by kosmospredanie**
gpseq: https://gitlab.com/kosmospredanie/gpseq

Closes #245

### CODE REVIEW

**Comment by kosmospredanie** [comment]
`Error processing tar file(exit status 1): write /var/www/html/purple/Purple.html.content.tpl: no space left on device`

What

**Comment by kosmospredanie** [comment]
I'll amend the commit to recheck.

**Comment by kosmospredanie** [comment]
`Error processing tar file(exit status 1): write /var/www/html/libcurl/Curl.CURLPROTO_FILE.html.navi.tpl: no space left on device`

It seems that it's not caused by this PR. Anyone?

**Comment by benwaffle** [comment]
Guessing the build VM ran out of space. Building all the docs takes up a lot of room

**Comment by kosmospredanie** [comment]
What should I do for the PR to be merged, then?

**Pull request merged**
