### PR TITLE
Add an example for Gee

### PR DESCRIPTION
**Pull request by rrthomas**
I have not been able to build valadoc-org yet, it complains:

```
warning: error: Package 'sdl2-net' not found
warning: error: Package 'sdl2-ttf' not found
warning: error: Package 'sdl2-mixer' not found
warning: error: Package 'sdl2-image' not found
warning: error: Package 'sdl2-gfx' not found
```

It seems to be unsure whether it's a warning or an error :) but it stops the build anyway.

### CODE REVIEW

**Comment by tintou** [comment]
The SDL issue has been fixed in https://github.com/vala-lang/valadoc-org/commit/c6bfd17e29ee8e35c0ee6a220761c32b00ed3f5c

**Comment by rrthomas** [comment]
Thanks, @tintou; I now get:

```
sdl2.vapi:1251.6-1251.7: error: unexpected token: <space>
   *  * "0"       - Non blocking.
```

**Comment by ricotz** [comment]
> Thanks, @tintou; I now get:
> 
> ```
> sdl2.vapi:1251.6-1251.7: error: unexpected token: <space>
>    *  * "0"       - Non blocking.
> ```

This should be fixed now.

**Comment by rrthomas** [comment]
@ricotz It's working now, many thanks!

**Review by tintou — APPROVED** [review]
Looks good to me

**Pull request merged**
