### PR TITLE
Add dark mode using prefers-color-scheme

### LINKED ISSUE #271: Feature Request: Support `prefers-color-scheme` CSS
Would be great if the site had a dark mode:

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### PR DESCRIPTION
**Pull request by jameswestman**
A basic dark mode stylesheet, using the prefers-color-scheme media query. Fixes #271.

Object hierarchy graphs are still black on white. I'm not sure how to fix that yet.

Also, should the search box be light-on-dark as well? I tried it but I'm not sure if it looks right.

### CODE REVIEW

**Comment by btkostner** [comment]
The object hierarchy graphs are going to be hard because they are generated svgs that have background colors set inline. I think the best route for that would be to generate SVGs without any color styles, then inline them in the HTML and use CSS to style them.

**Comment by flyingpimonster** [comment]
@btkostner I'm guessing that'll need to be fixed in valadoc, rather than here?

**Comment by btkostner** [comment]
@flyingpimonster I think so. @benwaffle or @flobrosch might have a better idea.

**Comment by benwaffle** [comment]
I believe the code is here - https://github.com/GNOME/vala/tree/mainline/libvaladoc/charts

it uses libgvc, part of graphviz, to generate the graphs

**Comment by CoderThomasB** [comment]
Any updates on this MR and when it is going to no longer be a draft?

**Comment by colinkiama** [comment]
I managed to render the graphs as inline SVGs. You can track the Pull/Merge Request for it here: https://gitlab.gnome.org/GNOME/vala/-/merge_requests/251

Here's what the styling changes and valadoc changes look like together:
Screen Shot 2022-07-31 at 01 30 19
Screen Shot 2022-07-31 at 01 30 26

Unfortunately, the tooltips that display symbol metadata when hovering over a graph node, don't appear when hovering over the SVG graphs. That's the last thing that needs to be worked out.

**Comment by colinkiama** [comment]
Documentation tooltips now over the graph nodes again:
valadoc-tooltip-over-svg-graph

**Comment by colinkiama** [comment]
If you want to test these changes yourself right now, you'll need to:
- Build valadoc from the branch in this merge merge request: https://gitlab.gnome.org/GNOME/vala/-/merge_requests/251
- Build valadoc-org:
    - Without the `--skip-existing` flag so doc pages always get rebuilt with the local valadoc tool.
    - Using the valadoc build with the inline svg graph changes

**Comment by colinkiama** [comment]
Inline SVG graph generation has been merged into Vala so we can proceed with this PR now.

Could somebody review this please?

**Review by colinkiama — APPROVED** [review]

**Pull request merged**
