### PR TITLE
Add goocanvas-2.0

### LINKED ISSUE #266: Add goocanvas
**Describe the bug**
I'm developing an app based on GooCanvas and repeadtly find myself turning between:

- https://valadoc.org 
- https://developer.gnome.org/goocanvas/stable/ (translating concepts from C to vala)

As a library to easily paint, I think it is worth to have it on valadoc.org

**To Reproduce**
GooCanvas is a library developed with GObject so its valadoc can be generated automatically

**Expected behavior**

**Screenshots**
Captura de pantalla de 2019-10-10 16-42-06

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser chrome

**Additional context**

Is there a general rule to publish a new library in valadoc.org, just to be sure. If I find other miss library I will try to provide directly the PR

### PR DESCRIPTION
**Pull request by benwaffle**
Fix #266

### CODE REVIEW

**Comment by benwaffle** [comment]
Good point, feel free to make the change, otherwise I'll do it tonight.

**Comment by ricotz** [comment]
This still requires to move the valadoc.org build to a newer vala version from `ppa:vala-team/next`

**Comment by benwaffle** [comment]
@ricotz why is a newer vala version needed for this PR?

**Comment by ricotz** [comment]
`goocanvas-2.0.vapi` is not part of vala-girs while it is shipped with vala itself since 0.44.0

**Comment by benwaffle** [comment]
Is there a way to make it use the latest libvaladoc-dev without having to hardcode the version number?

**Comment by ricotz** [comment]
I guess not. If a virtual package can be satisfied by more than one package it requires some version specification to avoid an ambiguous reference.

**Comment by albfan** [comment]
Although this PR is merged there're no results on valadoc.org, any ideas?

**Comment by benwaffle** [comment]
@btkostner what's the status on deployment? does it use the docker image? does it re-deploy when a new image is published?

**Comment by btkostner** [comment]
@benwaffle not yet

**Comment by albfan** [comment]
I understand that something should be done manually? anything we can do to turn it into an automatic step?

**Comment by btkostner** [comment]
@albfan Just some server work that needs to be done

**Pull request merged**
