### PR TITLE
Fix Granite repo default branch name

### PR DESCRIPTION
**Pull request by salim-b**

### CODE REVIEW

**Review by danirabbit — APPROVED** [review]
Thanks for updating this!

**Comment by danirabbit** [comment]
Oh wait nevermind. This is actually correct as in. `granite` and `granite-7` point to different branches intentionally

**Comment by salim-b** [comment]
Ok, I see. In that case, the branch names could be more intuitive, I guess...

**Comment by danirabbit** [comment]
Yeah that's a great point. It ended up like that just kind of a consequence of development and not really intentionally

**Pull request closed without merging**
