### PR TITLE
Adding VDA bindings documentation

### PR DESCRIPTION
**Pull request by esodan**
I would like to merge this as external packages, because they are from master. In the future I would like to differentiate from development to master and install a VAPI in this site.

### CODE REVIEW

**Comment by esodan** [comment]
This is related to https://github.com/vala-lang/valadoc-org/issues/244#issue-467812476

**Comment by benwaffle** [comment]
can we get the vapis in https://github.com/nemequ/vala-girs or https://gitlab.gnome.org/GNOME/vala-extra-vapis?

**Comment by esodan** [comment]
Sorry for a late response, I was improving and re-manufacturing the API in VDA, in order to be able to distribute as a more stable API.

@benwaffle VDA is a Vala written project and distributes its VAPI and introspection GIRS, are there any relation of valadoc-org and the above projects in a sense of a "must" be included there in order to be included in valodoc.org?

**Comment by benwaffle** [comment]
They don't have to be included, as we can link externally, but if you want the VDA docs to be searchable, have tooltips, and nicely integrated, then they need to be included.

**Comment by esodan** [comment]
@benwaffle While I see some check not successfull and after review them, the errores are about missing `valadoc-0.46` package.

What can I do to help here?

**Comment by benwaffle** [comment]
@esodan let's not specify `--pkg` args here. You already have partially complete `.deps` files here e.g. https://github.com/nemequ/vala-girs/blob/master/vala/vapi/vda-1.deps

You just need to fix these extra errors that I get when removing all the `--pkg` args
```
===== vda-1 =====
valadoc --target-glib 2.98 --driver "0.46" --importdir girs --doclet "." -o "tmp/vda-1" "girs/vala/vapi/vda-1.vapi" --vapidir "girs/vala/vapi" --girdir "girs/gir-1.0"  --use-svg-images -X --disable-devhelp --importdir "girs/gir-1.0" --import Vda-1 --wiki documentation/vda-1/wiki
vda-1.vapi:104.62-104.75: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:469.54-469.67: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:915.19-915.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:915.19-915.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:915.19-915.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1151.19-1151.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1151.19-1151.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1151.19-1151.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1166.44-1166.57: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:1244.46-1244.61: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1315.43-1315.56: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:1562.48-1562.61: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:2219.30-2219.38: error: The type name `GLib.File' could not be found
vda-1.vapi:2220.30-2220.38: error: The type name `GLib.File' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2400.45-2400.58: error: The type name `GLib.ListModel' could not be found
Command-line option `--driver` is deprecated and will be ignored
Failed: 18 error(s), 0 warning(s)
===== vgpg-1 =====
valadoc --target-glib 2.98 --driver "0.46" --importdir girs --doclet "." -o "tmp/vgpg-1" "girs/vala/vapi/vgpg-1.vapi" --vapidir "girs/vala/vapi" --girdir "girs/gir-1.0"  --use-svg-images -X --disable-devhelp --importdir "girs/gir-1.0" --import Vgpg-1 --wiki documentation/vgpg-1/wiki
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
Command-line option `--driver` is deprecated and will be ignored
Failed: 3 error(s), 0 warning(s)
===== vgsl-1 =====
valadoc --target-glib 2.98 --driver "0.46" --importdir girs --doclet "." -o "tmp/vgsl-1" "girs/vala/vapi/vgsl-1.vapi" --vapidir "girs/vala/vapi" --girdir "girs/gir-1.0"  --use-svg-images -X --disable-devhelp --importdir "girs/gir-1.0" --import Vgsl-1 --wiki documentation/vgsl-1/wiki
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
Command-line option `--driver` is deprecated and will be ignored
Failed: 3 error(s), 0 warning(s)
===== vgda-1 =====
valadoc --target-glib 2.98 --driver "0.46" --importdir girs --doclet "." -o "tmp/vgda-1" "girs/vala/vapi/vgda-1.vapi" --vapidir "girs/vala/vapi" --girdir "girs/gir-1.0"  --use-svg-images -X --disable-devhelp --importdir "girs/gir-1.0" --import Vgda-1 --wiki documentation/vgda-1/wiki
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
Command-line option `--driver` is deprecated and will be ignored
Failed: 3 error(s), 0 warning(s)
===== vpg-1 =====
valadoc --target-glib 2.98 --driver "0.46" --importdir girs --doclet "." -o "tmp/vpg-1" "girs/vala/vapi/vpg-1.vapi" --vapidir "girs/vala/vapi" --girdir "girs/gir-1.0"  --use-svg-images -X --disable-devhelp --importdir "girs/gir-1.0" --import Vpg-1 --wiki documentation/vpg-1/wiki
vda-1.vapi:104.62-104.75: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:469.54-469.67: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:915.19-915.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:915.19-915.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:915.19-915.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1151.19-1151.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1151.19-1151.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1151.19-1151.34: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1166.44-1166.57: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:1244.46-1244.61: error: The type name `GLib.Cancellable' could not be found
vda-1.vapi:1315.43-1315.56: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:1562.48-1562.61: error: The type name `GLib.ListModel' could not be found
vda-1.vapi:2219.30-2219.38: error: The type name `GLib.File' could not be found
vda-1.vapi:2220.30-2220.38: error: The type name `GLib.File' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2307.19-2307.23: error: The symbol `GCalc' could not be found
vda-1.vapi:2400.45-2400.58: error: The type name `GLib.ListModel' could not be found
Command-line option `--driver` is deprecated and will be ignored
Failed: 18 error(s), 0 warning(s)
```

**Comment by esodan** [comment]
https://github.com/nemequ/vala-girs/pull/15 New MR to fix reported errors, once in place a new commit removing all `--pkg` switches will be created.

**Comment by benwaffle** [comment]
@esodan it builds locally now without any extra flags. Will merge once CI passes.

**Pull request merged**
